-- ============================================================
-- Cira : 이슈 및 워크플로우 (Phase 1)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_CIRA_ISSUE_TYPE (이슈 타입 정의)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_CIRA_ISSUE_TYPE
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    TYPE_NM         VARCHAR(50)  NOT NULL, -- Epic | Story | Task | Bug | Sub-task
    ICON            VARCHAR(100),
    COLOR_CD        VARCHAR(7),
    DESCR           VARCHAR(255),
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_CIRA_ISSUE_TYPE PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_CIRA_ISSUE_TYPE_NM UNIQUE (TYPE_NM)
);

COMMENT ON TABLE SN_CIRA_CIRA_ISSUE_TYPE IS '이슈 타입 정의';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.TYPE_NM IS '타입명 (Epic | Story | Task | Bug | Sub-task)';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.ICON IS '아이콘 URL/클래스';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.COLOR_CD IS '색상 코드 (HEX)';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.DESCR IS '타입 설명';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_CIRA_ISSUE_TYPE.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_ISSUE (이슈 기본 정보)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE_STATUS
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    PROJECT_ID      VARCHAR(100),                                -- NULL = 전역 상태
    STATUS_NM       VARCHAR(50)  NOT NULL,                       -- To Do | In Progress | In Review | Done
    CATEGORY        VARCHAR(20)  NOT NULL DEFAULT 'IN_PROGRESS', -- TODO | IN_PROGRESS | DONE
    COLOR_CD        VARCHAR(7),
    SORT_ORD        SMALLINT     NOT NULL DEFAULT 0,
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE_STATUS PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_ISSUE_STATUS UNIQUE (PROJECT_ID, STATUS_NM),
    CONSTRAINT FK_SN_CIRA_ISSUE_STATUS_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_ISSUE_STATUS_PROJECT_ID ON SN_CIRA_ISSUE_STATUS (PROJECT_ID);

COMMENT ON TABLE SN_CIRA_ISSUE_STATUS IS '이슈 상태 정의';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.PROJECT_ID IS '프로젝트 ID (NULL=전역, FK → SN_CIRA_PROJECT)';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.STATUS_NM IS '상태명 (To Do | In Progress | In Review | Done)';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.CATEGORY IS '상태 카테고리 (TODO | IN_PROGRESS | DONE)';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.COLOR_CD IS '색상 코드 (HEX)';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.SORT_ORD IS '정렬 순서';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_ISSUE_STATUS.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 3. SN_CIRA_ISSUE (이슈 기본 정보)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    PROJECT_ID      VARCHAR(100) NOT NULL,
    SPRINT_ID       VARCHAR(100),
    ISSUE_KEY       VARCHAR(30)  NOT NULL,                  -- 예: CRA-42
    TITLE           VARCHAR(500) NOT NULL,
    CONTENT         TEXT,
    ISSUE_TYPE_ID   VARCHAR(100) NOT NULL,
    STATUS_ID       VARCHAR(100) NOT NULL,
    PRIORITY        VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM', -- HIGHEST | HIGH | MEDIUM | LOW | LOWEST
    STORY_PNT       NUMERIC(5, 1),
    ASSIGNEE_ID     VARCHAR(100),
    REPORTER_ID     VARCHAR(100) NOT NULL,
    DUE_DT          DATE,
    STARTED_AT      TIMESTAMP,
    RESOLVED_AT     TIMESTAMP,
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_ISSUE_KEY UNIQUE (ISSUE_KEY),
    CONSTRAINT FK_SN_CIRA_ISSUE_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_SPRINT FOREIGN KEY (SPRINT_ID) REFERENCES SN_CIRA_SPRINT (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_CIRA_ISSUE_TYPE FOREIGN KEY (ISSUE_TYPE_ID) REFERENCES SN_CIRA_CIRA_ISSUE_TYPE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_STATUS FOREIGN KEY (STATUS_ID) REFERENCES SN_CIRA_ISSUE_STATUS (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_ASSIGNEE FOREIGN KEY (ASSIGNEE_ID) REFERENCES GS_USER (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_REPORTER FOREIGN KEY (REPORTER_ID) REFERENCES GS_USER (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_ISSUE_PROJECT_ID ON SN_CIRA_ISSUE (PROJECT_ID);
CREATE INDEX IDX_SN_CIRA_ISSUE_SPRINT_ID ON SN_CIRA_ISSUE (SPRINT_ID);
CREATE INDEX IDX_SN_CIRA_ISSUE_STATUS_ID ON SN_CIRA_ISSUE (STATUS_ID);
CREATE INDEX IDX_SN_CIRA_ISSUE_ASSIGNEE_ID ON SN_CIRA_ISSUE (ASSIGNEE_ID);
CREATE INDEX IDX_SN_CIRA_ISSUE_PRIORITY ON SN_CIRA_ISSUE (PROJECT_ID, PRIORITY);

COMMENT ON TABLE SN_CIRA_ISSUE IS '이슈 기본 정보';
COMMENT ON COLUMN SN_CIRA_ISSUE.PROJECT_ID IS '프로젝트 ID (FK → SN_CIRA_PROJECT)';
COMMENT ON COLUMN SN_CIRA_ISSUE.SPRINT_ID IS '스프린트 ID (FK → SN_CIRA_SPRINT)';
COMMENT ON COLUMN SN_CIRA_ISSUE.ISSUE_KEY IS '이슈 키 (UK, 예: CRA-42)';
COMMENT ON COLUMN SN_CIRA_ISSUE.TITLE IS '이슈 제목';
COMMENT ON COLUMN SN_CIRA_ISSUE.CONTENT IS '이슈 본문';
COMMENT ON COLUMN SN_CIRA_ISSUE.ISSUE_TYPE_ID IS '이슈 타입 ID (FK → SN_CIRA_CIRA_ISSUE_TYPE)';
COMMENT ON COLUMN SN_CIRA_ISSUE.STATUS_ID IS '이슈 상태 ID (FK → SN_CIRA_ISSUE_STATUS)';
COMMENT ON COLUMN SN_CIRA_ISSUE.PRIORITY IS '우선순위 (HIGHEST | HIGH | MEDIUM | LOW | LOWEST)';
COMMENT ON COLUMN SN_CIRA_ISSUE.STORY_PNT IS '스토리 포인트';
COMMENT ON COLUMN SN_CIRA_ISSUE.ASSIGNEE_ID IS '담당자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_ISSUE.REPORTER_ID IS '보고자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_ISSUE.DUE_DT IS '마감일';
COMMENT ON COLUMN SN_CIRA_ISSUE.STARTED_AT IS '작업 시작일시';
COMMENT ON COLUMN SN_CIRA_ISSUE.RESOLVED_AT IS '해결일시';
COMMENT ON COLUMN SN_CIRA_ISSUE.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_ISSUE.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_ISSUE.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_ISSUE.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_ISSUE.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_ISSUE.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_ISSUE.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_ISSUE.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_ISSUE.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_ISSUE.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_ISSUE.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 4. SN_CIRA_ISSUE (이슈 기본 정보)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE_TRANSITION
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    PROJECT_ID      VARCHAR(100), -- NULL = 전역 규칙
    FROM_STATUS_ID  VARCHAR(100), -- NULL = 모든 상태
    TO_STATUS_ID    VARCHAR(100) NOT NULL,
    ALLOW_YN        VARCHAR(1)   NOT NULL DEFAULT 'Y',
    REQUIRED_ROLE   VARCHAR(50),
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE_TRANSITION PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_TRANSITION_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_TRANSITION_FROM_STATUS FOREIGN KEY (FROM_STATUS_ID) REFERENCES SN_CIRA_ISSUE_STATUS (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_TRANSITION_TO_STATUS FOREIGN KEY (TO_STATUS_ID) REFERENCES SN_CIRA_ISSUE_STATUS (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_ISSUE_TRANSITION_PROJECT ON SN_CIRA_ISSUE_TRANSITION (PROJECT_ID);

COMMENT ON TABLE SN_CIRA_ISSUE_TRANSITION IS '이슈 상태 전이 규칙';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.PROJECT_ID IS '프로젝트 ID (NULL=전역, FK → SN_CIRA_PROJECT)';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.FROM_STATUS_ID IS '출발 상태 ID (NULL=모든 상태, FK → SN_CIRA_ISSUE_STATUS)';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.TO_STATUS_ID IS '도착 상태 ID (FK → SN_CIRA_ISSUE_STATUS)';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.ALLOW_YN IS '전이 허용 여부 (Y | N)';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.REQUIRED_ROLE IS '전이 가능 역할 제한';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_ISSUE_TRANSITION.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 5. SN_CIRA_ISSUE (이슈 기본 정보)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE_LOG
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    ISSUE_ID        VARCHAR(100) NOT NULL,
    FIELD_NM        VARCHAR(100) NOT NULL,
    OLD_VAL         TEXT,
    NEW_VAL         TEXT,
    CHANGED_BY      VARCHAR(100) NOT NULL,
    CHANGED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE_LOG PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_LOG_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_LOG_CHANGER FOREIGN KEY (CHANGED_BY) REFERENCES GS_USER (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_ISSUE_LOG_ISSUE_ID ON SN_CIRA_ISSUE_LOG (ISSUE_ID);
CREATE INDEX IDX_SN_CIRA_ISSUE_LOG_CHANGED_AT ON SN_CIRA_ISSUE_LOG (ISSUE_ID, CHANGED_AT DESC);

COMMENT ON TABLE SN_CIRA_ISSUE_LOG IS '이슈 변경 이력';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.ISSUE_ID IS '이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.FIELD_NM IS '변경 필드명';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.OLD_VAL IS '변경 전 값';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.NEW_VAL IS '변경 후 값';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.CHANGED_BY IS '변경자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.CHANGED_AT IS '변경일시';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_ISSUE_LOG.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 6. SN_CIRA_ISSUE (이슈 기본 정보)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE_WATCHER
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    ISSUE_ID        VARCHAR(100) NOT NULL,
    USER_ID         VARCHAR(100) NOT NULL,
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE_WATCHER PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_ISSUE_WATCHER UNIQUE (ISSUE_ID, USER_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_WATCHER_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_WATCHER_USER FOREIGN KEY (USER_ID) REFERENCES GS_USER (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_ISSUE_WATCHER_USER_ID ON SN_CIRA_ISSUE_WATCHER (USER_ID);

COMMENT ON TABLE SN_CIRA_ISSUE_WATCHER IS '이슈 감시자';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.ISSUE_ID IS '이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.USER_ID IS '감시자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_ISSUE_WATCHER.MODIFIED_AT IS '수정일시';
