-- ============================================================
-- Cira : 칸반 보드 (Phase 1)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_BOARD (칸반/스크럼 보드)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_BOARD
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    PROJECT_ID      VARCHAR(100) NOT NULL,
    BOARD_NM        VARCHAR(200) NOT NULL,
    BOARD_TYPE      VARCHAR(20)  NOT NULL DEFAULT 'KANBAN', -- KANBAN | SCRUM
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_BOARD PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_BOARD_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_BOARD_PROJECT_ID ON SN_CIRA_BOARD (PROJECT_ID);

COMMENT ON TABLE SN_CIRA_BOARD IS '칸반/스크럼 보드';
COMMENT ON COLUMN SN_CIRA_BOARD.PROJECT_ID IS '프로젝트 ID (FK → SN_CIRA_PROJECT)';
COMMENT ON COLUMN SN_CIRA_BOARD.BOARD_NM IS '보드명';
COMMENT ON COLUMN SN_CIRA_BOARD.BOARD_TYPE IS '보드 유형 (KANBAN | SCRUM)';
COMMENT ON COLUMN SN_CIRA_BOARD.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_BOARD.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_BOARD.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_BOARD.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_BOARD.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_BOARD.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_BOARD.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_BOARD.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_BOARD.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_BOARD.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_BOARD.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_BOARD.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_BOARD.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_BOARD (칸반/스크럼 보드)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_BOARD_COLUMN
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    BOARD_ID        VARCHAR(100) NOT NULL,
    STATUS_ID       VARCHAR(100) NOT NULL,
    COLUMN_NM       VARCHAR(100) NOT NULL,
    WIP_LIMIT       SMALLINT, -- NULL = 제한 없음
    SORT_ORD        SMALLINT     NOT NULL DEFAULT 0,
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_BOARD_COLUMN PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_BOARD_COLUMN_ORD UNIQUE (BOARD_ID, SORT_ORD),
    CONSTRAINT FK_SN_CIRA_BOARD_COLUMN_BOARD FOREIGN KEY (BOARD_ID) REFERENCES SN_CIRA_BOARD (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_BOARD_COLUMN_STATUS FOREIGN KEY (STATUS_ID) REFERENCES SN_CIRA_ISSUE_STATUS (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_BOARD_COLUMN_STATUS_ID ON SN_CIRA_BOARD_COLUMN (STATUS_ID);

COMMENT ON TABLE SN_CIRA_BOARD_COLUMN IS '보드 컬럼';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.BOARD_ID IS '보드 ID (FK → SN_CIRA_BOARD)';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.STATUS_ID IS '연결 이슈 상태 ID (FK → SN_CIRA_ISSUE_STATUS)';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.COLUMN_NM IS '컬럼명';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.WIP_LIMIT IS 'WIP 제한 (NULL=제한 없음)';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.SORT_ORD IS '컬럼 정렬 순서';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_BOARD_COLUMN.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 3. SN_CIRA_ISSUE_POSITION (보드 내 이슈 위치 (Lexorank))

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE_POSITION
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    ISSUE_ID        VARCHAR(100) NOT NULL,
    COLUMN_ID       VARCHAR(100) NOT NULL,
    RANK_STR        VARCHAR(100) NOT NULL, -- Lexorank 정렬 문자열
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE_POSITION PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_ISSUE_POSITION UNIQUE (ISSUE_ID, COLUMN_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_POSITION_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_POSITION_COLUMN FOREIGN KEY (COLUMN_ID) REFERENCES SN_CIRA_BOARD_COLUMN (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_ISSUE_POSITION_COLUMN_ID ON SN_CIRA_ISSUE_POSITION (COLUMN_ID);
CREATE INDEX IDX_SN_CIRA_ISSUE_POSITION_RANK ON SN_CIRA_ISSUE_POSITION (COLUMN_ID, RANK_STR);

COMMENT ON TABLE SN_CIRA_ISSUE_POSITION IS '보드 내 이슈 위치 (Lexorank)';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.ISSUE_ID IS '이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.COLUMN_ID IS '보드 컬럼 ID (FK → SN_CIRA_BOARD_COLUMN)';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.RANK_STR IS 'Lexorank 정렬 문자열';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_ISSUE_POSITION.MODIFIED_AT IS '수정일시';
