-- ============================================================
-- Cira : 커스텀 필드 — EAV 패턴 (Phase 2)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_CUSTOM_FIELD (커스텀 필드 정의)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_CUSTOM_FIELD
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    PROJECT_ID      VARCHAR(100),          -- NULL = 전역 필드
    FIELD_NM        VARCHAR(100) NOT NULL,
    FIELD_TYPE      VARCHAR(30)  NOT NULL, -- TEXT | NUMBER | DATE | DATETIME | SELECT | MULTI_SELECT | USER | URL | CHECKBOX
    REQUIRED_YN     VARCHAR(1)   NOT NULL DEFAULT 'N',
    OPTIONS         JSONB,                 -- SELECT / MULTI_SELECT 선택지 목록
    SORT_ORD        SMALLINT     NOT NULL DEFAULT 0,
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_CUSTOM_FIELD PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_CUSTOM_FIELD UNIQUE (PROJECT_ID, FIELD_NM),
    CONSTRAINT FK_SN_CIRA_CUSTOM_FIELD_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_CUSTOM_FIELD_PROJECT_ID ON SN_CIRA_CUSTOM_FIELD (PROJECT_ID);

COMMENT ON TABLE SN_CIRA_CUSTOM_FIELD IS '커스텀 필드 정의';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.PROJECT_ID IS '프로젝트 ID (NULL=전역, FK → SN_CIRA_PROJECT)';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.FIELD_NM IS '필드명';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.FIELD_TYPE IS '필드 유형 (TEXT | NUMBER | DATE | SELECT …)';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.REQUIRED_YN IS '필수 여부 (Y | N)';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.OPTIONS IS 'SELECT/MULTI_SELECT 선택지 목록 (JSONB)';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.SORT_ORD IS '정렬 순서';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_CUSTOM_FIELD.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_ISSUE_CF_VALUE (이슈별 커스텀 필드 값)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE_CF_VALUE
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    ISSUE_ID        VARCHAR(100) NOT NULL,
    CUSTOM_FIELD_ID VARCHAR(100) NOT NULL,
    VAL_TEXT        TEXT,
    VAL_NUMBER      NUMERIC(20, 4),
    VAL_DT          DATE,
    VAL_JSON        JSONB, -- SELECT | MULTI_SELECT | USER 등 복합 값
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE_CF_VALUE PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_ISSUE_CF_VALUE UNIQUE (ISSUE_ID, CUSTOM_FIELD_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_CF_VALUE_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_CF_VALUE_CUSTOM_FIELD FOREIGN KEY (CUSTOM_FIELD_ID) REFERENCES SN_CIRA_CUSTOM_FIELD (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_ISSUE_CF_VALUE_ISSUE_ID ON SN_CIRA_ISSUE_CF_VALUE (ISSUE_ID);
CREATE INDEX IDX_SN_CIRA_ISSUE_CF_VALUE_FIELD_ID ON SN_CIRA_ISSUE_CF_VALUE (CUSTOM_FIELD_ID);

COMMENT ON TABLE SN_CIRA_ISSUE_CF_VALUE IS '이슈별 커스텀 필드 값';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.ISSUE_ID IS '이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.CUSTOM_FIELD_ID IS '커스텀 필드 ID (FK → SN_CIRA_CUSTOM_FIELD)';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.VAL_TEXT IS '텍스트 값';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.VAL_NUMBER IS '숫자 값';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.VAL_DT IS '날짜 값';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.VAL_JSON IS '복합 값 (JSONB)';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_ISSUE_CF_VALUE.MODIFIED_AT IS '수정일시';
