-- ============================================================
-- Cira : 예산 및 시간 추적 (Phase 2)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_PROJECT_BUDGET (프로젝트 예산)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_PROJECT_BUDGET
(
    OBJ_ID          VARCHAR(100)   NOT NULL,
    PROJECT_ID      VARCHAR(100)   NOT NULL,
    TOTAL_BUDGET    NUMERIC(15, 2) NOT NULL,
    BUDGET_CATEGORY VARCHAR(50)    NOT NULL DEFAULT 'TOTAL', -- TOTAL | DEVELOPMENT | DESIGN | QA | OTHER
    CURRENCY        VARCHAR(3)     NOT NULL DEFAULT 'KRW',
    FISCAL_YEAR     SMALLINT,
    -- BaseModel
    SRV_ID          VARCHAR(50)    NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)    NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100)   NOT NULL,
    USE_STAT_CD     VARCHAR(40)    NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100)   NOT NULL,
    PREV_EVNT_NM    VARCHAR(100),
    ACT_CD          VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP      NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP      NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_PROJECT_BUDGET PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_PROJECT_BUDGET_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_PROJECT_BUDGET_PROJECT_ID ON SN_CIRA_PROJECT_BUDGET (PROJECT_ID);

COMMENT
ON TABLE SN_CIRA_PROJECT_BUDGET IS '프로젝트 예산';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.PROJECT_ID IS '프로젝트 ID (FK → SN_CIRA_PROJECT)';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.TOTAL_BUDGET IS '총 예산';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.BUDGET_CATEGORY IS '예산 카테고리 (TOTAL | DEVELOPMENT | DESIGN | QA | OTHER)';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.CURRENCY IS '통화 코드 (KRW | USD …)';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.FISCAL_YEAR IS '회계 연도';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_PROJECT_BUDGET.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_HOURLY_RATE (사용자별 시급)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_HOURLY_RATE
(
    OBJ_ID       VARCHAR(100)   NOT NULL,
    USER_ID      VARCHAR(100)   NOT NULL,
    HOURLY_RATE  NUMERIC(10, 2) NOT NULL,
    CURRENCY     VARCHAR(3)     NOT NULL DEFAULT 'KRW',
    EFF_FROM_DT  DATE           NOT NULL,
    EFF_TO_DT    DATE,
    -- BaseModel
    SRV_ID       VARCHAR(50)    NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)    NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100)   NOT NULL,
    USE_STAT_CD  VARCHAR(40)    NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100)   NOT NULL,
    PREV_EVNT_NM VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP      NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP      NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_HOURLY_RATE PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_HOURLY_RATE_USER FOREIGN KEY (USER_ID) REFERENCES GS_USER (OBJ_ID),
    CONSTRAINT CHK_SN_CIRA_HOURLY_RATE_DATES CHECK (EFF_TO_DT IS NULL OR EFF_TO_DT > EFF_FROM_DT)
);


CREATE INDEX IDX_SN_CIRA_HOURLY_RATE_USER_ID ON SN_CIRA_HOURLY_RATE (USER_ID, EFF_FROM_DT DESC);

COMMENT
ON TABLE SN_CIRA_HOURLY_RATE IS '사용자별 시급';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.USER_ID IS '사용자 ID (FK → GS_USER)';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.HOURLY_RATE IS '시급';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.CURRENCY IS '통화 코드';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.EFF_FROM_DT IS '적용 시작일';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.EFF_TO_DT IS '적용 종료일 (NULL=현재 적용 중)';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_HOURLY_RATE.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 3. SN_CIRA_TIME_LOG (시간 기록)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_TIME_LOG
(
    OBJ_ID       VARCHAR(100)  NOT NULL,
    ISSUE_ID     VARCHAR(100)  NOT NULL,
    USER_ID      VARCHAR(100)  NOT NULL,
    LOG_HRS      NUMERIC(6, 2) NOT NULL,
    LOG_DT       DATE          NOT NULL DEFAULT CURRENT_DATE,
    DESCR        TEXT,
    -- BaseModel
    SRV_ID       VARCHAR(50)   NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)   NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100)  NOT NULL,
    USE_STAT_CD  VARCHAR(40)   NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100)  NOT NULL,
    PREV_EVNT_NM VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP     NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP     NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_TIME_LOG PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_TIME_LOG_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_TIME_LOG_USER FOREIGN KEY (USER_ID) REFERENCES GS_USER (OBJ_ID),
    CONSTRAINT CHK_SN_CIRA_TIME_LOG_HRS CHECK (LOG_HRS > 0 AND LOG_HRS <= 24)
);


CREATE INDEX IDX_SN_CIRA_TIME_LOG_ISSUE_ID ON SN_CIRA_TIME_LOG (ISSUE_ID);
CREATE INDEX IDX_SN_CIRA_TIME_LOG_USER_ID ON SN_CIRA_TIME_LOG (USER_ID);
CREATE INDEX IDX_SN_CIRA_TIME_LOG_LOG_DT ON SN_CIRA_TIME_LOG (LOG_DT);

COMMENT
ON TABLE SN_CIRA_TIME_LOG IS '시간 기록';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.ISSUE_ID IS '이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.USER_ID IS '사용자 ID (FK → GS_USER)';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.LOG_HRS IS '기록 시간 (시간 단위, 0 < LOG_HRS ≤ 24)';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.LOG_DT IS '작업 날짜';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.DESCR IS '작업 설명';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_TIME_LOG.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 4. SN_CIRA_EXPENSE (지출 기록)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_EXPENSE
(
    OBJ_ID       VARCHAR(100)   NOT NULL,
    PROJECT_ID   VARCHAR(100)   NOT NULL,
    ISSUE_ID     VARCHAR(100),
    AMOUNT       NUMERIC(15, 2) NOT NULL,
    CURRENCY     VARCHAR(3)     NOT NULL DEFAULT 'KRW',
    CATEGORY     VARCHAR(50)    NOT NULL, -- LABOR | SOFTWARE | INFRA | EQUIPMENT | OTHER
    EXPENSE_DT   DATE           NOT NULL,
    DESCR        TEXT,
    -- BaseModel
    SRV_ID       VARCHAR(50)    NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)    NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100)   NOT NULL,
    USE_STAT_CD  VARCHAR(40)    NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100)   NOT NULL,
    PREV_EVNT_NM VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP      NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP      NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_EXPENSE PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_EXPENSE_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_EXPENSE_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_EXPENSE_PROJECT_ID ON SN_CIRA_EXPENSE (PROJECT_ID);
CREATE INDEX IDX_SN_CIRA_EXPENSE_DT ON SN_CIRA_EXPENSE (PROJECT_ID, EXPENSE_DT);

COMMENT
ON TABLE SN_CIRA_EXPENSE IS '지출 기록';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.PROJECT_ID IS '프로젝트 ID (FK → SN_CIRA_PROJECT)';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.ISSUE_ID IS '이슈 ID (FK → SN_CIRA_ISSUE, 선택)';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.AMOUNT IS '지출 금액';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.CURRENCY IS '통화 코드';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.CATEGORY IS '지출 카테고리 (LABOR | SOFTWARE | INFRA | EQUIPMENT | OTHER)';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.EXPENSE_DT IS '지출 날짜';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.DESCR IS '지출 설명';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_EXPENSE.MODIFIED_AT IS '수정일시';
