-- ============================================================
-- Cira : 워크플로우 자동화 엔진 (Phase 2)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_AUTO_RULE (워크플로우 자동화 규칙)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_AUTO_RULE
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    PROJECT_ID   VARCHAR(100),                           -- NULL = 전역 규칙
    RULE_NM      VARCHAR(200) NOT NULL,
    DESCR        TEXT,
    TRIGGER_TYPE VARCHAR(50)  NOT NULL,                  -- ISSUE_CREATED | STATUS_CHANGED | ASSIGNED | COMMENT_ADDED | SPRINT_STARTED | SPRINT_COMPLETED | SCHEDULED
    COND         JSONB,                                  -- 트리거 조건 (예: {"status":"In Review"})
    ACTION       JSONB        NOT NULL,                  -- 실행 액션 (예: {"type":"ASSIGN"})
    -- BaseModel (USE_STAT_CD로 활성/비활성 관리) �??�성/비활??관�?
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable', -- Usable(활성) | Disabled(비활성)
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_AUTO_RULE PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_AUTO_RULE_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_AUTO_RULE_PROJECT_ID ON SN_CIRA_AUTO_RULE (PROJECT_ID);
CREATE INDEX IDX_SN_CIRA_AUTO_RULE_TRIGGER_TYPE ON SN_CIRA_AUTO_RULE (TRIGGER_TYPE) WHERE USE_STAT_CD = 'Usable';

COMMENT
ON TABLE SN_CIRA_AUTO_RULE IS '워크플로우 자동화 규칙';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.PROJECT_ID IS '프로젝트 ID (NULL=전역, FK → SN_CIRA_PROJECT)';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.RULE_NM IS '규칙명';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.DESCR IS '규칙 설명';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.TRIGGER_TYPE IS '트리거 유형 (ISSUE_CREATED | STATUS_CHANGED …)';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.COND IS '트리거 조건 (JSONB)';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.ACTION IS '실행 액션 (JSONB)';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_AUTO_RULE.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_AUTO_EXECUTION (자동화 실행 기록)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_AUTO_EXECUTION
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    RULE_ID      VARCHAR(100) NOT NULL,
    ISSUE_ID     VARCHAR(100),
    EXEC_STAT    VARCHAR(20)  NOT NULL DEFAULT 'SUCCESS', -- SUCCESS | FAILED | SKIPPED
    ERR_MSG      TEXT,
    EXECUTED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_AUTO_EXECUTION PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_AUTO_EXECUTION_RULE FOREIGN KEY (RULE_ID) REFERENCES SN_CIRA_AUTO_RULE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_AUTO_EXECUTION_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_AUTO_EXECUTION_RULE_ID ON SN_CIRA_AUTO_EXECUTION (RULE_ID);
CREATE INDEX IDX_SN_CIRA_AUTO_EXECUTION_ISSUE_ID ON SN_CIRA_AUTO_EXECUTION (ISSUE_ID) WHERE ISSUE_ID IS NOT NULL;
CREATE INDEX IDX_SN_CIRA_AUTO_EXECUTION_EXECUTED_AT ON SN_CIRA_AUTO_EXECUTION (EXECUTED_AT DESC);

COMMENT
ON TABLE SN_CIRA_AUTO_EXECUTION IS '자동화 실행 기록';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.RULE_ID IS '자동화 규칙 ID (FK → SN_CIRA_AUTO_RULE)';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.ISSUE_ID IS '연관 이슈 ID (FK → SN_CIRA_ISSUE, 선택)';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.EXEC_STAT IS '실행 결과 (SUCCESS | FAILED | SKIPPED)';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.ERR_MSG IS '오류 메시지';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.EXECUTED_AT IS '실행일시';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_AUTO_EXECUTION.MODIFIED_AT IS '수정일시';
