-- ============================================================
-- Cira : 알림 및 감사 이력 (Phase 2)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_NOTIFICATION (알림)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_NOTIFICATION
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    USER_ID         VARCHAR(100) NOT NULL,
    NOTIF_TYPE      VARCHAR(50)  NOT NULL, -- ISSUE_ASSIGNED | COMMENT_ADDED | STATUS_CHANGED | MENTIONED | SPRINT_STARTED …
    TITLE           VARCHAR(300) NOT NULL,
    MSG             TEXT,
    RESOURCE_TYPE   VARCHAR(50),           -- ISSUE | PROJECT | SPRINT | COMMENT
    RESOURCE_ID     VARCHAR(100),
    READ_YN         VARCHAR(1)   NOT NULL DEFAULT 'N',
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_NOTIFICATION PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_NOTIFICATION_USER FOREIGN KEY (USER_ID) REFERENCES GS_USER (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_NOTIFICATION_USER_ID ON SN_CIRA_NOTIFICATION (USER_ID, READ_YN, CREATED_AT DESC);
CREATE INDEX IDX_SN_CIRA_NOTIFICATION_CREATED ON SN_CIRA_NOTIFICATION (CREATED_AT DESC);

COMMENT ON TABLE SN_CIRA_NOTIFICATION IS '알림';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.USER_ID IS '수신자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.NOTIF_TYPE IS '알림 유형 (ISSUE_ASSIGNED | COMMENT_ADDED …)';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.TITLE IS '알림 제목';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.MSG IS '알림 내용';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.RESOURCE_TYPE IS '연관 리소스 유형 (ISSUE | PROJECT | SPRINT | COMMENT)';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.RESOURCE_ID IS '연관 리소스 ID';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.READ_YN IS '읽음 여부 (Y | N)';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_NOTIFICATION.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_NOTIF_PREF (알림 수신 설정)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_NOTIF_PREF
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    USER_ID         VARCHAR(100) NOT NULL,
    CHANNEL         VARCHAR(30)  NOT NULL, -- EMAIL | IN_APP | SLACK | WEBHOOK
    EVENT_TYPE      VARCHAR(50)  NOT NULL, -- ISSUE_ASSIGNED | COMMENT_ADDED | … | ALL
    ENABLED_YN      VARCHAR(1)   NOT NULL DEFAULT 'Y',
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_NOTIF_PREF PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_NOTIF_PREF UNIQUE (USER_ID, CHANNEL, EVENT_TYPE),
    CONSTRAINT FK_SN_CIRA_NOTIF_PREF_USER FOREIGN KEY (USER_ID) REFERENCES GS_USER (OBJ_ID)
);

COMMENT ON TABLE SN_CIRA_NOTIF_PREF IS '알림 수신 설정';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.USER_ID IS '사용자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.CHANNEL IS '알림 채널 (EMAIL | IN_APP | SLACK | WEBHOOK)';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.EVENT_TYPE IS '이벤트 유형 (ISSUE_ASSIGNED | ALL …)';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.ENABLED_YN IS '알림 활성 여부 (Y | N)';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_NOTIF_PREF.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 3. SN_CIRA_AUDIT_LOG (감사 로그 (월별 파티셔닝))

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_AUDIT_LOG
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    ACTION_TYPE     VARCHAR(30)  NOT NULL, -- CREATE | UPDATE | DELETE | LOGIN | LOGOUT
    ACTOR_ID        VARCHAR(100),
    RESOURCE_TYPE   VARCHAR(50)  NOT NULL, -- ISSUE | PROJECT | USER | ROLE …
    RESOURCE_ID     VARCHAR(100) NOT NULL,
    OLD_SNAPSHOT    JSONB,
    NEW_SNAPSHOT    JSONB,
    IP_ADDR         VARCHAR(45),
    USER_AGENT      TEXT,
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_AUDIT_LOG PRIMARY KEY (OBJ_ID, CREATED_AT)
) PARTITION BY RANGE (CREATED_AT);

-- 파티션 예시 (월별 분리)
CREATE TABLE SN_CIRA_AUDIT_LOG_2026_05 PARTITION OF SN_CIRA_AUDIT_LOG
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE SN_CIRA_AUDIT_LOG_2026_06 PARTITION OF SN_CIRA_AUDIT_LOG
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');


CREATE INDEX IDX_SN_CIRA_AUDIT_LOG_ACTOR ON SN_CIRA_AUDIT_LOG (ACTOR_ID);
CREATE INDEX IDX_SN_CIRA_AUDIT_LOG_RESOURCE ON SN_CIRA_AUDIT_LOG (RESOURCE_TYPE, RESOURCE_ID);
CREATE INDEX IDX_SN_CIRA_AUDIT_LOG_CREATED ON SN_CIRA_AUDIT_LOG (CREATED_AT DESC);

COMMENT ON TABLE SN_CIRA_AUDIT_LOG IS '감사 로그 (월별 파티셔닝)';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.ACTION_TYPE IS '액션 유형 (CREATE | UPDATE | DELETE | LOGIN | LOGOUT)';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.ACTOR_ID IS '행위자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.RESOURCE_TYPE IS '리소스 유형 (ISSUE | PROJECT | USER …)';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.RESOURCE_ID IS '리소스 ID';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.OLD_SNAPSHOT IS '변경 전 데이터 스냅샷 (JSONB)';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.NEW_SNAPSHOT IS '변경 후 데이터 스냅샷 (JSONB)';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.IP_ADDR IS '요청 IP 주소';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.USER_AGENT IS '요청 User-Agent';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_AUDIT_LOG.MODIFIED_AT IS '수정일시';
