-- ============================================================
-- Cira : Git 연동 (Phase 2)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_GIT_REPO (Git 저장소 정보)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_GIT_REPO
(
    OBJ_ID           VARCHAR(100) NOT NULL,
    PROJECT_ID       VARCHAR(100) NOT NULL,
    PROVIDER         VARCHAR(20)  NOT NULL DEFAULT 'GITHUB', -- GITHUB | GITLAB | BITBUCKET
    REPO_URL         VARCHAR(500) NOT NULL,
    ACCESS_TOKEN_ENC TEXT,                                   -- 암호화된 액세스 토큰
    DEFAULT_BRANCH   VARCHAR(100) NOT NULL DEFAULT 'main',
    -- BaseModel (USE_STAT_CD로 활성/비활성 관리)
    SRV_ID           VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT           VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID         VARCHAR(100) NOT NULL,
    USE_STAT_CD      VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM          VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD           VARCHAR(100),
    ACT_CM           TEXT,
    CREATED_BY       VARCHAR(40),
    CREATED_AT       TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY      VARCHAR(40),
    MODIFIED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_GIT_REPO PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_GIT_REPO UNIQUE (PROJECT_ID, REPO_URL),
    CONSTRAINT FK_SN_CIRA_GIT_REPO_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_GIT_REPO_PROJECT_ID ON SN_CIRA_GIT_REPO (PROJECT_ID);

COMMENT
ON TABLE SN_CIRA_GIT_REPO IS 'Git 저장소 정보';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.PROJECT_ID IS '프로젝트 ID (FK → SN_CIRA_PROJECT)';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.PROVIDER IS 'Git 공급자 (GITHUB | GITLAB | BITBUCKET)';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.REPO_URL IS '저장소 URL';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.ACCESS_TOKEN_ENC IS '암호화된 액세스 토큰';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.DEFAULT_BRANCH IS '기본 브랜치명';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_GIT_REPO.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_GIT_COMMIT (Git 커밋 정보)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_GIT_COMMIT
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    REPO_ID      VARCHAR(100) NOT NULL,
    ISSUE_ID     VARCHAR(100),
    COMMIT_HASH  VARCHAR(40)  NOT NULL,
    MSG          TEXT         NOT NULL,
    AUTHOR_NM    VARCHAR(100),
    AUTHOR_EMAIL VARCHAR(255),
    COMMIT_DT    TIMESTAMP    NOT NULL,
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_GIT_COMMIT PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_GIT_COMMIT UNIQUE (REPO_ID, COMMIT_HASH),
    CONSTRAINT FK_SN_CIRA_GIT_COMMIT_REPO FOREIGN KEY (REPO_ID) REFERENCES SN_CIRA_GIT_REPO (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_GIT_COMMIT_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_GIT_COMMIT_REPO_ID ON SN_CIRA_GIT_COMMIT (REPO_ID);
CREATE INDEX IDX_SN_CIRA_GIT_COMMIT_ISSUE_ID ON SN_CIRA_GIT_COMMIT (ISSUE_ID) WHERE ISSUE_ID IS NOT NULL;
CREATE INDEX IDX_SN_CIRA_GIT_COMMIT_DT ON SN_CIRA_GIT_COMMIT (COMMIT_DT DESC);

COMMENT
ON TABLE SN_CIRA_GIT_COMMIT IS 'Git 커밋 정보';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.REPO_ID IS '저장소 ID (FK → SN_CIRA_GIT_REPO)';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.ISSUE_ID IS '연관 이슈 ID (FK → SN_CIRA_ISSUE, 선택)';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.COMMIT_HASH IS '커밋 해시 (40자)';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.MSG IS '커밋 메시지';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.AUTHOR_NM IS '커밋 작성자명';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.AUTHOR_EMAIL IS '커밋 작성자 이메일';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.COMMIT_DT IS '커밋 일시';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_GIT_COMMIT.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 3. SN_CIRA_GIT_PR (Git Pull Request 정보)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_GIT_PR
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    REPO_ID      VARCHAR(100) NOT NULL,
    ISSUE_ID     VARCHAR(100),
    PR_NO        INTEGER      NOT NULL,
    TITLE        VARCHAR(500) NOT NULL,
    DESCR        TEXT,
    PR_STAT      VARCHAR(20)  NOT NULL DEFAULT 'OPEN', -- OPEN | MERGED | CLOSED | DRAFT
    SRC_BRANCH   VARCHAR(200),
    TGT_BRANCH   VARCHAR(200),
    AUTHOR_NM    VARCHAR(100),
    AUTHOR_EMAIL VARCHAR(255),
    MERGED_AT    TIMESTAMP,
    CLOSED_AT    TIMESTAMP,
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_GIT_PR PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_GIT_PR UNIQUE (REPO_ID, PR_NO),
    CONSTRAINT FK_SN_CIRA_GIT_PR_REPO FOREIGN KEY (REPO_ID) REFERENCES SN_CIRA_GIT_REPO (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_GIT_PR_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_GIT_PR_REPO_ID ON SN_CIRA_GIT_PR (REPO_ID);
CREATE INDEX IDX_SN_CIRA_GIT_PR_ISSUE_ID ON SN_CIRA_GIT_PR (ISSUE_ID) WHERE ISSUE_ID IS NOT NULL;
CREATE INDEX IDX_SN_CIRA_GIT_PR_STAT ON SN_CIRA_GIT_PR (REPO_ID, PR_STAT);

COMMENT
ON TABLE SN_CIRA_GIT_PR IS 'Git Pull Request 정보';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.REPO_ID IS '저장소 ID (FK → SN_CIRA_GIT_REPO)';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.ISSUE_ID IS '연관 이슈 ID (FK → SN_CIRA_ISSUE, 선택)';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.PR_NO IS 'PR 번호 (저장소 내 고유)';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.TITLE IS 'PR 제목';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.DESCR IS 'PR 설명';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.PR_STAT IS 'PR 상태 (OPEN | MERGED | CLOSED | DRAFT)';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.SRC_BRANCH IS '소스 브랜치';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.TGT_BRANCH IS '대상 브랜치';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.AUTHOR_NM IS 'PR 작성자명';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.AUTHOR_EMAIL IS 'PR 작성자 이메일';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.MERGED_AT IS '병합일시';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.CLOSED_AT IS '닫힌 일시';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_GIT_PR.MODIFIED_AT IS '수정일시';
