-- ============================================================
-- Cira : 버전 및 마일스톤 (Phase 2)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_VERSION (릴리스 버전)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_VERSION
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    PROJECT_ID      VARCHAR(100) NOT NULL,
    VERSION_NM      VARCHAR(100) NOT NULL,
    DESCR           TEXT,
    PLAN_REL_DT     DATE,
    RELEASED_DT     DATE,
    -- BaseModel (USE_STAT_CD: Usable=Unreleased | Released | Archived)
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_VERSION PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_VERSION UNIQUE (PROJECT_ID, VERSION_NM),
    CONSTRAINT FK_SN_CIRA_VERSION_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_VERSION_PROJECT_ID ON SN_CIRA_VERSION (PROJECT_ID);
CREATE INDEX IDX_SN_CIRA_VERSION_STAT ON SN_CIRA_VERSION (PROJECT_ID, USE_STAT_CD);

COMMENT ON TABLE SN_CIRA_VERSION IS '릴리스 버전';
COMMENT ON COLUMN SN_CIRA_VERSION.PROJECT_ID IS '프로젝트 ID (FK → SN_CIRA_PROJECT)';
COMMENT ON COLUMN SN_CIRA_VERSION.VERSION_NM IS '버전명 (UK per project)';
COMMENT ON COLUMN SN_CIRA_VERSION.DESCR IS '버전 설명';
COMMENT ON COLUMN SN_CIRA_VERSION.PLAN_REL_DT IS '릴리스 예정일';
COMMENT ON COLUMN SN_CIRA_VERSION.RELEASED_DT IS '실제 릴리스일';
COMMENT ON COLUMN SN_CIRA_VERSION.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_VERSION.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_VERSION.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_VERSION.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_VERSION.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_VERSION.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_VERSION.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_VERSION.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_VERSION.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_VERSION.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_VERSION.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_VERSION.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_VERSION.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_ISSUE_VERSION (이슈-버전 매핑)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE_VERSION
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    ISSUE_ID        VARCHAR(100) NOT NULL,
    VERSION_ID      VARCHAR(100) NOT NULL,
    REL_TYPE        VARCHAR(30)  NOT NULL DEFAULT 'FIX_VERSION', -- FIX_VERSION | AFFECTS_VERSION
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE_VERSION PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_ISSUE_VERSION UNIQUE (ISSUE_ID, VERSION_ID, REL_TYPE),
    CONSTRAINT FK_SN_CIRA_ISSUE_VERSION_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_VERSION_VERSION FOREIGN KEY (VERSION_ID) REFERENCES SN_CIRA_VERSION (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_ISSUE_VERSION_VERSION_ID ON SN_CIRA_ISSUE_VERSION (VERSION_ID);

COMMENT ON TABLE SN_CIRA_ISSUE_VERSION IS '이슈-버전 매핑';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.ISSUE_ID IS '이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.VERSION_ID IS '버전 ID (FK → SN_CIRA_VERSION)';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.REL_TYPE IS '관계 유형 (FIX_VERSION | AFFECTS_VERSION)';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_ISSUE_VERSION.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 3. SN_CIRA_MILESTONE (마일스톤)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_MILESTONE
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    PROJECT_ID      VARCHAR(100) NOT NULL,
    MILESTONE_NM    VARCHAR(200) NOT NULL,
    DESCR           TEXT,
    DUE_DT          DATE,
    -- BaseModel (USE_STAT_CD: Usable=Open | Closed)
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_MILESTONE PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_MILESTONE_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_MILESTONE_PROJECT_ID ON SN_CIRA_MILESTONE (PROJECT_ID);

COMMENT ON TABLE SN_CIRA_MILESTONE IS '마일스톤';
COMMENT ON COLUMN SN_CIRA_MILESTONE.PROJECT_ID IS '프로젝트 ID (FK → SN_CIRA_PROJECT)';
COMMENT ON COLUMN SN_CIRA_MILESTONE.MILESTONE_NM IS '마일스톤명';
COMMENT ON COLUMN SN_CIRA_MILESTONE.DESCR IS '마일스톤 설명';
COMMENT ON COLUMN SN_CIRA_MILESTONE.DUE_DT IS '목표 완료일';
COMMENT ON COLUMN SN_CIRA_MILESTONE.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_MILESTONE.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_MILESTONE.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_MILESTONE.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_MILESTONE.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_MILESTONE.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_MILESTONE.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_MILESTONE.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_MILESTONE.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_MILESTONE.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_MILESTONE.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_MILESTONE.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_MILESTONE.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 4. SN_CIRA_MILESTONE (마일스톤)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_MILESTONE_ISSUE
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    MILESTONE_ID    VARCHAR(100) NOT NULL,
    ISSUE_ID        VARCHAR(100) NOT NULL,
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_MILESTONE_ISSUE PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_MILESTONE_ISSUE UNIQUE (MILESTONE_ID, ISSUE_ID),
    CONSTRAINT FK_SN_CIRA_MILESTONE_ISSUE_MILESTONE FOREIGN KEY (MILESTONE_ID) REFERENCES SN_CIRA_MILESTONE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_MILESTONE_ISSUE_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_MILESTONE_ISSUE_ISSUE_ID ON SN_CIRA_MILESTONE_ISSUE (ISSUE_ID);

COMMENT ON TABLE SN_CIRA_MILESTONE_ISSUE IS '마일스톤-이슈 매핑';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.MILESTONE_ID IS '마일스톤 ID (FK → SN_CIRA_MILESTONE)';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.ISSUE_ID IS '이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_MILESTONE_ISSUE.MODIFIED_AT IS '수정일시';
