-- ============================================================
-- Cira : 검색 및 저장 필터 (Phase 2)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- DB    : PostgreSQL (Full-Text Search)

-- ----------------------------------------------------------
-- 1. SN_CIRA_SAVED_FILTER (저장된 검색 필터)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_SAVED_FILTER
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    USER_ID         VARCHAR(100) NOT NULL,
    PROJECT_ID      VARCHAR(100), -- NULL = 전역 필터
    FILTER_NM       VARCHAR(200) NOT NULL,
    JQL_QUERY       TEXT         NOT NULL,
    SHARED_YN       VARCHAR(1)   NOT NULL DEFAULT 'N',
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_SAVED_FILTER PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_SAVED_FILTER_USER FOREIGN KEY (USER_ID) REFERENCES GS_USER (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_SAVED_FILTER_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_SAVED_FILTER_USER_ID ON SN_CIRA_SAVED_FILTER (USER_ID);
CREATE INDEX IDX_SN_CIRA_SAVED_FILTER_PROJECT_ID ON SN_CIRA_SAVED_FILTER (PROJECT_ID) WHERE PROJECT_ID IS NOT NULL;

COMMENT ON TABLE SN_CIRA_SAVED_FILTER IS '저장된 검색 필터';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.USER_ID IS '소유자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.PROJECT_ID IS '프로젝트 ID (NULL=전역, FK → SN_CIRA_PROJECT)';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.FILTER_NM IS '필터명';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.JQL_QUERY IS 'JQL 쿼리 문자열';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.SHARED_YN IS '공유 여부 (Y | N)';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_SAVED_FILTER.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_ISSUE_SEARCH_IDX (이슈 Full-Text Search 인덱스)
--    Elasticsearch 도입 시 대체 / 병행 사용 가능

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE_SEARCH_IDX
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    ISSUE_ID        VARCHAR(100) NOT NULL,
    SEARCH_VEC      TSVECTOR,
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE_SEARCH_IDX PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_ISSUE_SEARCH_IDX UNIQUE (ISSUE_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_SEARCH_IDX_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID) ON DELETE CASCADE
);


-- GIN 인덱스 (Full-Text Search 최적화)
CREATE INDEX IDX_SN_CIRA_ISSUE_SEARCH_VEC ON SN_CIRA_ISSUE_SEARCH_IDX USING GIN (SEARCH_VEC);

COMMENT ON TABLE SN_CIRA_ISSUE_SEARCH_IDX IS '이슈 Full-Text Search 인덱스';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.ISSUE_ID IS '이슈 ID (UK, FK → SN_CIRA_ISSUE)';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.SEARCH_VEC IS 'PostgreSQL TSVECTOR (GIN 인덱스 대상)';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_ISSUE_SEARCH_IDX.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 3. FTS 자동 갱신 트리거

-- ----------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_sync_issue_search_vec()
    RETURNS TRIGGER AS
$$
BEGIN
    INSERT INTO SN_CIRA_ISSUE_SEARCH_IDX
    (OBJ_ID, ISSUE_ID, SEARCH_VEC, SRV_ID, TENANT, TRACE_ID, USE_STAT_CD, EVNT_NM, CREATED_BY, CREATED_AT, MODIFIED_BY,
     MODIFIED_AT)
    VALUES (gen_random_uuid()::TEXT,
            NEW.OBJ_ID,
            TO_TSVECTOR('simple',
                        COALESCE(NEW.ISSUE_KEY, '') || ' ' ||
                        COALESCE(NEW.TITLE, '') || ' ' ||
                        COALESCE(NEW.CONTENT, '')
            ),
            NEW.SRV_ID, NEW.TENANT, NEW.TRACE_ID, 'Usable', 'SyncSearchVec',
            NEW.CREATED_BY, NOW(), NEW.MODIFIED_BY, NOW())
    ON CONFLICT (ISSUE_ID) DO UPDATE
        SET SEARCH_VEC  = EXCLUDED.SEARCH_VEC,
            MODIFIED_AT = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_SN_CIRA_ISSUE_SEARCH_SYNC
    AFTER INSERT OR UPDATE OF TITLE, CONTENT
    ON SN_CIRA_ISSUE
    FOR EACH ROW
EXECUTE FUNCTION fn_sync_issue_search_vec();
