-- Flyway Migration: V150__sn_cira_attachment_uploaded_by
-- SN_CIRA_ATTACHMENT 테이블에 업로더 정보 컬럼 추가
-- Generated: 2026-05-27

ALTER TABLE SN_CIRA_ATTACHMENT
    ADD COLUMN IF NOT EXISTS UPLOADED_BY VARCHAR(100);

COMMENT ON COLUMN SN_CIRA_ATTACHMENT.UPLOADED_BY IS '업로드한 사용자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_ATTACHMENT.FILE_PATH IS 'S3(MinIO) 오브젝트 키 (attachments/{projectId}/{issueId}/{uuid}_{fileName})';

CREATE INDEX IF NOT EXISTS IDX_SN_CIRA_ATTACHMENT_UPLOADED_BY
    ON SN_CIRA_ATTACHMENT (UPLOADED_BY);
