-- Flyway Migration: V20__sn_projects_and_sprints
-- Source: 02_projects_and_sprints.sql
-- Generated: 2026-05-25

-- ============================================================
-- Cira : 프로젝트 및 스프린트 (Phase 1)
-- Prefix: SN_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_PROJECT (프로젝트 기본 정보)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_PROJECT
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    PROJECT_KEY  VARCHAR(20)  NOT NULL,   -- 예: CRA, TAS
    PROJECT_NM   VARCHAR(200) NOT NULL,
    DESCR        TEXT,
    PROJECT_TYPE VARCHAR(30)  NOT NULL DEFAULT 'SCRUM',   -- SCRUM | KANBAN
    OWNER_ID     VARCHAR(100),
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',  -- Usable | Archived | Deleted
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_PROJECT          PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_PROJECT_KEY      UNIQUE (PROJECT_KEY),
    CONSTRAINT FK_SN_CIRA_PROJECT_OWNER    FOREIGN KEY (OWNER_ID) REFERENCES GS_USER(OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_PROJECT_USE_STAT ON SN_CIRA_PROJECT (USE_STAT_CD);

COMMENT ON TABLE SN_CIRA_PROJECT IS '프로젝트 기본 정보';
COMMENT ON COLUMN SN_CIRA_PROJECT.PROJECT_KEY IS '프로젝트 키 (UK, 예: CRA)';
COMMENT ON COLUMN SN_CIRA_PROJECT.PROJECT_NM IS '프로젝트명';
COMMENT ON COLUMN SN_CIRA_PROJECT.DESCR IS '프로젝트 설명';
COMMENT ON COLUMN SN_CIRA_PROJECT.PROJECT_TYPE IS '프로젝트 유형 (SCRUM | KANBAN)';
COMMENT ON COLUMN SN_CIRA_PROJECT.OWNER_ID IS '프로젝트 소유자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_PROJECT.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_PROJECT.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_PROJECT.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_PROJECT.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_PROJECT.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_PROJECT.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_PROJECT.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_PROJECT.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_PROJECT.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_PROJECT.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_PROJECT.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_PROJECT.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_PROJECT.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_PROJECT (프로젝트 기본 정보)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_PROJECT_MEMBER
(
    OBJ_ID      VARCHAR(100) NOT NULL,
    PROJECT_ID  VARCHAR(100) NOT NULL,
    USER_ID     VARCHAR(100) NOT NULL,
    ROLE        VARCHAR(50)  NOT NULL DEFAULT 'DEVELOPER',  -- ADMIN | DEVELOPER | REPORTER | VIEWER
    -- BaseModel
    SRV_ID      VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT      VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID    VARCHAR(100) NOT NULL,
    USE_STAT_CD VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM     VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM      TEXT,
    CREATED_BY  VARCHAR(40),
    CREATED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY VARCHAR(40),
    MODIFIED_AT TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_PROJECT_MEMBER          PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_PROJECT_MEMBER          UNIQUE (PROJECT_ID, USER_ID),
    CONSTRAINT FK_SN_CIRA_PROJECT_MEMBER_PROJECT  FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT(OBJ_ID),
    CONSTRAINT FK_SN_CIRA_PROJECT_MEMBER_USER     FOREIGN KEY (USER_ID)    REFERENCES GS_USER(OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_PROJECT_MEMBER_USER_ID ON SN_CIRA_PROJECT_MEMBER (USER_ID);

COMMENT ON TABLE SN_CIRA_PROJECT_MEMBER IS '프로젝트 멤버';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.PROJECT_ID IS '프로젝트 ID (FK → SN_CIRA_PROJECT)';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.USER_ID IS '사용자 ID (FK → GS_USER)';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.ROLE IS '프로젝트 내 역할 (ADMIN | DEVELOPER | REPORTER | VIEWER)';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_PROJECT_MEMBER.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 3. SN_CIRA_SPRINT (스프린트)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_SPRINT
(
    OBJ_ID      VARCHAR(100) NOT NULL,
    PROJECT_ID  VARCHAR(100) NOT NULL,
    SPRINT_NM   VARCHAR(200) NOT NULL,
    GOAL        TEXT,
    START_DT    DATE,
    END_DT      DATE,
    -- BaseModel
    SRV_ID      VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT      VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID    VARCHAR(100) NOT NULL,
    USE_STAT_CD VARCHAR(40)  NOT NULL DEFAULT 'Usable',  -- Planned | Active | Completed
    EVNT_NM     VARCHAR(100) NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM      TEXT,
    CREATED_BY  VARCHAR(40),
    CREATED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY VARCHAR(40),
    MODIFIED_AT TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_SPRINT            PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_SPRINT_PROJECT    FOREIGN KEY (PROJECT_ID) REFERENCES SN_CIRA_PROJECT(OBJ_ID),
    CONSTRAINT CHK_SN_CIRA_SPRINT_DATES     CHECK (END_DT IS NULL OR START_DT IS NULL OR END_DT >= START_DT)
);


CREATE INDEX IDX_SN_CIRA_SPRINT_PROJECT_ID ON SN_CIRA_SPRINT (PROJECT_ID);
CREATE INDEX IDX_SN_CIRA_SPRINT_STATUS     ON SN_CIRA_SPRINT (PROJECT_ID, USE_STAT_CD);

COMMENT ON TABLE SN_CIRA_SPRINT IS '스프린트';
COMMENT ON COLUMN SN_CIRA_SPRINT.PROJECT_ID IS '프로젝트 ID (FK → SN_CIRA_PROJECT)';
COMMENT ON COLUMN SN_CIRA_SPRINT.SPRINT_NM IS '스프린트명';
COMMENT ON COLUMN SN_CIRA_SPRINT.GOAL IS '스프린트 목표';
COMMENT ON COLUMN SN_CIRA_SPRINT.START_DT IS '시작일';
COMMENT ON COLUMN SN_CIRA_SPRINT.END_DT IS '종료일';
COMMENT ON COLUMN SN_CIRA_SPRINT.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_SPRINT.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_SPRINT.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_SPRINT.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_SPRINT.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_SPRINT.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_SPRINT.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_SPRINT.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_SPRINT.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_SPRINT.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_SPRINT.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_SPRINT.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_SPRINT.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 4. SN_CIRA_SPRINT (스프린트)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_SPRINT_METRICS
(
    OBJ_ID                 VARCHAR(100)  NOT NULL,
    SPRINT_ID              VARCHAR(100)  NOT NULL,
    VELOCITY               NUMERIC(10,2),
    TEAM_CAPACITY          NUMERIC(10,2),
    PLAN_STORY_PNT         NUMERIC(10,2),
    COMPL_STORY_PNT        NUMERIC(10,2),
    -- BaseModel
    SRV_ID                 VARCHAR(50)   NOT NULL DEFAULT 'CIRA',
    TENANT                 VARCHAR(50)   NOT NULL DEFAULT 'TAS',
    TRACE_ID               VARCHAR(100)  NOT NULL,
    USE_STAT_CD            VARCHAR(40)   NOT NULL DEFAULT 'Usable',
    EVNT_NM                VARCHAR(100)  NOT NULL,
    PREV_EVNT_NM     VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM                 TEXT,
    CREATED_BY             VARCHAR(40),
    CREATED_AT             TIMESTAMP     NOT NULL DEFAULT NOW(),
    MODIFIED_BY            VARCHAR(40),
    MODIFIED_AT            TIMESTAMP     NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_SPRINT_METRICS         PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_SPRINT_METRICS         UNIQUE (SPRINT_ID),
    CONSTRAINT FK_SN_CIRA_SPRINT_METRICS_SPRINT  FOREIGN KEY (SPRINT_ID) REFERENCES SN_CIRA_SPRINT(OBJ_ID)
);

COMMENT ON TABLE SN_CIRA_SPRINT_METRICS IS '스프린트 메트릭';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.SPRINT_ID IS '스프린트 ID (FK → SN_CIRA_SPRINT)';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.VELOCITY IS '완료 스토리 포인트 (Velocity)';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.TEAM_CAPACITY IS '팀 가용 공수 (시간)';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.PLAN_STORY_PNT IS '계획 스토리 포인트';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.COMPL_STORY_PNT IS '완료 스토리 포인트';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.SRV_ID IS '서비스명';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.TENANT IS '테넌트';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.TRACE_ID IS '트레이스 ID';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.USE_STAT_CD IS '사용 상태';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.ACT_CD IS '액션 사유 코드';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.ACT_CM IS '액션 코멘트';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.CREATED_BY IS '생성자';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.CREATED_AT IS '생성일시';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.MODIFIED_BY IS '수정자';
COMMENT ON COLUMN SN_CIRA_SPRINT_METRICS.MODIFIED_AT IS '수정일시';
