-- Flyway Migration: V40__sn_issue_relations
-- Source: 04_issue_relations.sql
-- Generated: 2026-05-25

-- ============================================================
-- Cira : 이슈 관계 및 의존성 (Phase 1)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_ISSUE_LINK (이슈 간 관계)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE_LINK
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    SRC_ISSUE_ID VARCHAR(100) NOT NULL,
    TGT_ISSUE_ID VARCHAR(100) NOT NULL,
    LINK_TYPE    VARCHAR(50)  NOT NULL, -- BLOCKS | IS_BLOCKED_BY | RELATES_TO | DUPLICATES | IS_DUPLICATED_BY | CLONES
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE_LINK PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_ISSUE_LINK UNIQUE (SRC_ISSUE_ID, TGT_ISSUE_ID, LINK_TYPE),
    CONSTRAINT FK_SN_CIRA_ISSUE_LINK_SRC FOREIGN KEY (SRC_ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_LINK_TGT FOREIGN KEY (TGT_ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT CHK_SN_CIRA_ISSUE_LINK_NO_SELF CHECK (SRC_ISSUE_ID <> TGT_ISSUE_ID)
);


CREATE INDEX IDX_SN_CIRA_ISSUE_LINK_SRC ON SN_CIRA_ISSUE_LINK (SRC_ISSUE_ID);
CREATE INDEX IDX_SN_CIRA_ISSUE_LINK_TGT ON SN_CIRA_ISSUE_LINK (TGT_ISSUE_ID);

COMMENT
ON TABLE SN_CIRA_ISSUE_LINK IS '이슈 간 관계';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.SRC_ISSUE_ID IS '출발 이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.TGT_ISSUE_ID IS '도착 이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.LINK_TYPE IS '관계 유형 (BLOCKS | IS_BLOCKED_BY | RELATES_TO | DUPLICATES …)';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_ISSUE_LINK.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_ISSUE_SUBTASK (부모-자식 이슈 관계)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ISSUE_SUBTASK
(
    OBJ_ID          VARCHAR(100) NOT NULL,
    PARENT_ISSUE_ID VARCHAR(100) NOT NULL,
    CHILD_ISSUE_ID  VARCHAR(100) NOT NULL,
    SORT_ORD        SMALLINT     NOT NULL DEFAULT 0,
    -- BaseModel
    SRV_ID          VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT          VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID        VARCHAR(100) NOT NULL,
    USE_STAT_CD     VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM         VARCHAR(100) NOT NULL,
    PREV_EVNT_NM    VARCHAR(100),
    ACT_CD          VARCHAR(100),
    ACT_CM          TEXT,
    CREATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY     VARCHAR(40),
    MODIFIED_AT     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ISSUE_SUBTASK PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_ISSUE_SUBTASK UNIQUE (PARENT_ISSUE_ID, CHILD_ISSUE_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_SUBTASK_PARENT FOREIGN KEY (PARENT_ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ISSUE_SUBTASK_CHILD FOREIGN KEY (CHILD_ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT CHK_SN_CIRA_ISSUE_SUBTASK_NO_SELF CHECK (PARENT_ISSUE_ID <> CHILD_ISSUE_ID)
);


CREATE INDEX IDX_SN_CIRA_ISSUE_SUBTASK_PARENT ON SN_CIRA_ISSUE_SUBTASK (PARENT_ISSUE_ID);
CREATE INDEX IDX_SN_CIRA_ISSUE_SUBTASK_CHILD ON SN_CIRA_ISSUE_SUBTASK (CHILD_ISSUE_ID);

COMMENT
ON TABLE SN_CIRA_ISSUE_SUBTASK IS '부모-자식 이슈 관계';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.PARENT_ISSUE_ID IS '부모 이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.CHILD_ISSUE_ID IS '자식 이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.SORT_ORD IS '자식 이슈 정렬 순서';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_ISSUE_SUBTASK.MODIFIED_AT IS '수정일시';
