-- Flyway Migration: V50__sn_comments_and_collab
-- Source: 05_comments_and_collaboration.sql
-- Generated: 2026-05-25

-- ============================================================
-- Cira : 댓글 및 협업 (Phase 1)
-- Prefix: SN_CIRA_ (Single App — Cira 전용)
-- DB    : PostgreSQL
-- ============================================================

-- ----------------------------------------------------------
-- 1. SN_CIRA_COMMENT (이슈 댓글)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_COMMENT
(
    OBJ_ID       VARCHAR(100) NOT NULL,
    ISSUE_ID     VARCHAR(100) NOT NULL,
    AUTHOR_ID    VARCHAR(100) NOT NULL,
    PARENT_ID    VARCHAR(100),                           -- 부모 댓글 ID (대댓글)
    CONTENT      TEXT         NOT NULL,
    -- BaseModel
    SRV_ID       VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100) NOT NULL,
    USE_STAT_CD  VARCHAR(40)  NOT NULL DEFAULT 'Usable', -- Usable | Deleted
    EVNT_NM      VARCHAR(100) NOT NULL,
    PREV_EVNT_NM VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_COMMENT PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_COMMENT_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_COMMENT_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES GS_USER (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_COMMENT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES SN_CIRA_COMMENT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_COMMENT_ISSUE_ID ON SN_CIRA_COMMENT (ISSUE_ID);
CREATE INDEX IDX_SN_CIRA_COMMENT_AUTHOR_ID ON SN_CIRA_COMMENT (AUTHOR_ID);
CREATE INDEX IDX_SN_CIRA_COMMENT_PARENT_ID ON SN_CIRA_COMMENT (PARENT_ID) WHERE PARENT_ID IS NOT NULL;

COMMENT
ON TABLE SN_CIRA_COMMENT IS '이슈 댓글';
COMMENT
ON COLUMN SN_CIRA_COMMENT.ISSUE_ID IS '이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT
ON COLUMN SN_CIRA_COMMENT.AUTHOR_ID IS '작성자 ID (FK → GS_USER)';
COMMENT
ON COLUMN SN_CIRA_COMMENT.PARENT_ID IS '부모 댓글 ID (대댓글, FK → SN_CIRA_COMMENT)';
COMMENT
ON COLUMN SN_CIRA_COMMENT.CONTENT IS '댓글 본문';
COMMENT
ON COLUMN SN_CIRA_COMMENT.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_COMMENT.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_COMMENT.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_COMMENT.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_COMMENT.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_COMMENT.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_COMMENT.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_COMMENT.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_COMMENT.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_COMMENT.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_COMMENT.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_COMMENT.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_COMMENT.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 2. SN_CIRA_COMMENT (이슈 댓글)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_COMMENT_REACTION
(
    OBJ_ID        VARCHAR(100) NOT NULL,
    COMMENT_ID    VARCHAR(100) NOT NULL,
    USER_ID       VARCHAR(100) NOT NULL,
    REACTION_TYPE VARCHAR(30)  NOT NULL, -- THUMBS_UP | THUMBS_DOWN | LAUGH | HOORAY | CONFUSED | HEART | ROCKET | EYES
    -- BaseModel
    SRV_ID        VARCHAR(50)  NOT NULL DEFAULT 'CIRA',
    TENANT        VARCHAR(50)  NOT NULL DEFAULT 'TAS',
    TRACE_ID      VARCHAR(100) NOT NULL,
    USE_STAT_CD   VARCHAR(40)  NOT NULL DEFAULT 'Usable',
    EVNT_NM       VARCHAR(100) NOT NULL,
    PREV_EVNT_NM  VARCHAR(100),
    ACT_CD        VARCHAR(100),
    ACT_CM        TEXT,
    CREATED_BY    VARCHAR(40),
    CREATED_AT    TIMESTAMP    NOT NULL DEFAULT NOW(),
    MODIFIED_BY   VARCHAR(40),
    MODIFIED_AT   TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_COMMENT_REACTION PRIMARY KEY (OBJ_ID),
    CONSTRAINT UK_SN_CIRA_COMMENT_REACTION UNIQUE (COMMENT_ID, USER_ID, REACTION_TYPE),
    CONSTRAINT FK_SN_CIRA_COMMENT_REACTION_COMMENT FOREIGN KEY (COMMENT_ID) REFERENCES SN_CIRA_COMMENT (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_COMMENT_REACTION_USER FOREIGN KEY (USER_ID) REFERENCES GS_USER (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_COMMENT_REACTION_COMMENT_ID ON SN_CIRA_COMMENT_REACTION (COMMENT_ID);

COMMENT
ON TABLE SN_CIRA_COMMENT_REACTION IS '댓글 반응 (이모지)';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.COMMENT_ID IS '댓글 ID (FK → SN_CIRA_COMMENT)';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.USER_ID IS '사용자 ID (FK → GS_USER)';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.REACTION_TYPE IS '반응 유형 (THUMBS_UP | HEART | ROCKET …)';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_COMMENT_REACTION.MODIFIED_AT IS '수정일시';

-- ----------------------------------------------------------
-- 3. SN_CIRA_ATTACHMENT (이슈 첨부 파일)

-- ----------------------------------------------------------
CREATE TABLE SN_CIRA_ATTACHMENT
(
    OBJ_ID       VARCHAR(100)  NOT NULL,
    ISSUE_ID     VARCHAR(100)  NOT NULL,
    COMMENT_ID   VARCHAR(100),
    FILE_NM      VARCHAR(255)  NOT NULL,
    FILE_PATH    VARCHAR(1000) NOT NULL,
    FILE_SIZE    BIGINT,
    MIME_TYPE    VARCHAR(100),
    -- BaseModel
    SRV_ID       VARCHAR(50)   NOT NULL DEFAULT 'CIRA',
    TENANT       VARCHAR(50)   NOT NULL DEFAULT 'TAS',
    TRACE_ID     VARCHAR(100)  NOT NULL,
    USE_STAT_CD  VARCHAR(40)   NOT NULL DEFAULT 'Usable',
    EVNT_NM      VARCHAR(100)  NOT NULL,
    PREV_EVNT_NM VARCHAR(100),
    ACT_CD       VARCHAR(100),
    ACT_CM       TEXT,
    CREATED_BY   VARCHAR(40),
    CREATED_AT   TIMESTAMP     NOT NULL DEFAULT NOW(),
    MODIFIED_BY  VARCHAR(40),
    MODIFIED_AT  TIMESTAMP     NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_SN_CIRA_ATTACHMENT PRIMARY KEY (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ATTACHMENT_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES SN_CIRA_ISSUE (OBJ_ID),
    CONSTRAINT FK_SN_CIRA_ATTACHMENT_COMMENT FOREIGN KEY (COMMENT_ID) REFERENCES SN_CIRA_COMMENT (OBJ_ID)
);


CREATE INDEX IDX_SN_CIRA_ATTACHMENT_ISSUE_ID ON SN_CIRA_ATTACHMENT (ISSUE_ID);

COMMENT
ON TABLE SN_CIRA_ATTACHMENT IS '이슈 첨부 파일';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.ISSUE_ID IS '이슈 ID (FK → SN_CIRA_ISSUE)';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.COMMENT_ID IS '댓글 ID (FK → SN_CIRA_COMMENT, 댓글 첨부 시)';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.FILE_NM IS '파일명';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.FILE_PATH IS '파일 저장 경로';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.FILE_SIZE IS '파일 크기 (bytes)';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.MIME_TYPE IS 'MIME 타입';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.OBJ_ID IS '오브젝트 ID (PK, UUID)';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.SRV_ID IS '서비스명';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.TENANT IS '테넌트';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.TRACE_ID IS '트레이스 ID';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.USE_STAT_CD IS '사용 상태';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.EVNT_NM IS '이벤트명';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.PREV_EVNT_NM IS '이전 이벤트명';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.ACT_CD IS '액션 사유 코드';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.ACT_CM IS '액션 코멘트';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.CREATED_BY IS '생성자';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.CREATED_AT IS '생성일시';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.MODIFIED_BY IS '수정자';
COMMENT
ON COLUMN SN_CIRA_ATTACHMENT.MODIFIED_AT IS '수정일시';
